### ISSUE TITLE
Scalaz-http Roadmap

### ISSUE THREAD

**Issue by emilypi** [scalaz/scalaz-http#3]
This issue is strictly discussion to nail down the featureset we'd like to support within `scalaz-http`, and any modules/submodules that would be good additions to the core codebase. The following have been proposed:

- [ ] core http support (client/server, JSON, derived JSON functionality, etc)
- [ ] Pure/Async Redis DSL
- [ ] Pure/Async Kafka DSL
- [ ] Pure/Async AWS Support (DynamoDB, EC2, etc)
- [ ] Integration with `scalaz-crypto`
- [ ] Integration with `scalaz-streams`

Additionally, to some degree we need to figure out a timeline for integrating Scalaz 8's features. We're currently operating on `7.2.17` as a default, which is totally and completely up for debate (throw out a number and we'll discuss it.

Your thoughts are welcome.

**Comment by NeQuissimus** [comment]
1) This is probably implicitly part of "Core http support", just want to point this out explicitly

- HTTP/2.0 should be a given
- Painless TLS using Java keystores
- Ability to disable certificate verification with TLS (so one can use self-signed certs quickly during tests)

2) Why would Kafka/Redis/AWS DSLs be part of an HTTP module? Seems to me they should integrate with `scalaz-streams` and then we can compose HTTP streams into Kafka streams etc.

**Comment by hrhino** [comment]
* AWS could be `scalaz-aws` or something, but I wouldn't be opposed to
having it be an artifact separate from "core http" which lives in this repo
(especially considering as it would need much of the http stuff).

* TLS support here should inform tsec/scalaz-crypto development and _vice
versa_, I think (ping @jmcardon).

* Apropos of gitter discussion, a fully statically-analyzable routing DSL
and related features like documentation generation would be ideal.

**Comment by emilypi** [comment]
@NeQuissimus I agree that things like many of the features suggested should be separate projects, since they will not be `http` specific. From the start, though, I'd like to make sure everyone is on board with the fact that this is going to be a very http-specific project, and we'll compose with other projects in the ecosystem as needed. 

- Absolutely HTTP/2.0 is a must
- I'm not sure how I feel about using Java Keystores. My experience with the api is limited, and I think that should be up to `scalaz-crypto` to manage DSL's surrounding any crypto libraries

**Comment by hrhino** [comment]
If Java keystores are needed, that should be provided by `scalaz-crypto`, and this project should use those APIs (preferably agnostic of the keystore impl).

As part of the `scalaz-crypto` project, of course, I hold a fully neutral and unbiased opinion of this.

**Comment by RaasAhsan** [comment]
Mentioned core HTTP support, I think it would also be a good idea to include some WebSocket support.

Will routing remain a user concern or will there be some good old generic routing functionality out-of-the-box?

**Comment by emilypi** [comment]
@RaasAhsan Out of the box would be preferable if we want people to use this thing, but allowing the user to specify would (I'm sure) be appreciated by many.

**Comment by RaasAhsan** [comment]
One way to do this is modeling the server as something like `HttpRequest => Task[HttpResponse]`, then offer generic routing utilities in a separate module. Any router would then just need to supply a function of that signature to the core server.

**Comment by emilypi** [comment]
@RaasAhsan We'll discuss this more. I got the feeling from the gitter chat that we wanted to do something different than the usually Kleisli-based/Monadic composition, and focus more on an Applicative approach. Join us and talk 😄

**Comment by jdegoes** [comment]
A couple of random thoughts:

I feel like `Request => Response` isn't a _bad_ way to model a _server_ (building such a thing, of course, can be done at a higher level with, e.g. applicative DSL). It's tried and true and has great composability (with routers, etc.). The disadvantage is that it commits you to having ADTs for all things HTTP, so you can create such a thing as an "HTTP request". 

For most applications, this approach is overly concrete and over-specified, as they only care about a few parts of the request and the rest doesn't matter — so why spend all this time parsing, validating as per RFC, creating data structures, and stuffing heap-allocated values into these data structures, all so a web service can ignore almost everything?

The advantage of a more abstract model is that, in theory, you can then generate something executable from this model, which then can blindly skip over parts of the request it doesn't care about. It only needs to fully parse and materialize specifics of the request that you actually care about, opening up the door to much higher performance.

In [RedEyes](https://github.com/redeyes/redeyes/tree/master/src/main/scala/redeyes/api), I planned to model services as (essentially) a triple of `Parser[A]`, `Parser[B]`, and `A => M[B]`. I wouldn't do exactly the same thing today, but the core idea here is that the input and output structure are described (to within a user-defined degree of precision), and decoupled from the actual provision of the service. 

These "parsers" were multi-channel parsers, meaning they could read independently from different parts of the request, and did not have to consume all the input to match (e.g. you could "parse" a specific header and ignore the rest). The parsers were also (almost) invertible, which means that you can not only translate from the request bytes to an `A`, but you can also translate from the `A` to request bytes, opening the door to inter-process communication (similarly, the response parser lets you go from `B` to the response bytes, but also from the response bytes to `B` again).

If the "DSL" describing the "parsers" operates at the level of the HTTP protocol, rather than, say, individual characters in a byte stream, then mere introspection of the parser allows you to generate documentation of the API. Possibly even client-libraries in some cases.

That all this can be done using a generalization of applicatives is very interesting. The only library to offer similar such functionality is Haskell's Servant, which uses type-level tricks to achieve these features. I suspect something like this for Scala, if it has excellent performance and the expressiveness to encode common web services, could quickly take the market by storm.

I do feel like the library should be streaming by default, designed to handle requests and responses of arbitrary size in constant space. Probably client libraries for AWS, etc., would make good "proof of viability", and I second the suggestion to place them in separate repos.

Also agreed on HTTP/2.0, and secure deployments.

More as I have time...
